version: "3.8"

x-app: &app-tpl
    image: node:14.16.1-alpine
    restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=docker
      - JAEGER_AGENT_HOST=jaeger
    networks:
      - jaeger-tracing-network
    volumes:
      - ./:/home/node/app

services:
  payment-service:
    <<: *app-tpl
    container_name: payment-service
    ports:
      - "9000:9000"
    command: "npm run start:dev payment-service"
  warehouse-service:
    <<: *app-tpl
    container_name: warehouse-service
    ports:
      - "9001:9000"
    command: "npm run start:dev warehouse-service"
  delivery-service:
    <<: *app-tpl
    container_name: delivery-service
    ports:
      - "9002:9000"
    command: "npm run start:dev delivery-service"
  coordinator-service:
    <<: *app-tpl
    container_name: coordinator-service
    ports:
      - "9003:9000"
    command: "npm run start:dev coordinator-service"
volumes:
  redis:

networks:
  jaeger-tracing-network:
