import { MigrationInterface, QueryRunner } from 'typeorm';

export class createWarehouseTable1634845072783 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const query = `
    CREATE TABLE warehouse ( 
    id bigint generated by default as identity(start with 1) primary key,    
    item_name varchar(40) NOT NULL,
    amount bigint NOT NULL,
    price bigint NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
    `;

    await queryRunner.query(query);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
